# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Climb' do
    pod 'Charts'
    #pod 'Mapbox-iOS-SDK'
    pod 'Mapbox-iOS-SDK', :podspec => 'https://raw.githubusercontent.com/mapbox/mapbox-gl-native/ios-v3.0.0-pre.4/ios/Mapbox-iOS-SDK.podspec'
    pod 'Parse'
    #disable bitcode
	#post_install do |installer|
    #	installer.pods_project.targets.each do |target|
     #   	target.build_configurations.each do |config|
      #      	config.build_settings['ENABLE_BITCODE'] = 'NO'
       # 	end
    	#end
	#end
end

target 'ClimbTests' do

end

target 'ClimbUITests' do

end

